### ISSUE TITLE
Seulement cliquer sur 'voir' permet d'accéder au contenu d'un élément

### ISSUE THREAD

**Issue by VermeulenWouter** [EPLStudents/eplstudents.github.io#4]
Faisant un 'hover' sur un élément il y a un effet de fond qui fait croire que l'élément est cliquable. Mais en réalité seul 'Voir' permet réellement à accéder le contenu derrière un panneau. 

![image](https://github.com/EPLStudents/eplstudents.github.io/assets/67514315/2e7e46d2-222f-4841-b71a-eeb5f281aa02)

**Comment by Hokkaydo** [comment]
Fixed in #5
