### ISSUE TITLE
Eduroam Banned

### ISSUE THREAD

**Issue by Tfloow** [EPLStudents/eplstudents.github.io#6]
The www.epl-students.be website is currently banned on UCL's eduroam. This may be due to a protection against entity trying to impersonate UCLouvain or any affiliated name.
We should write an email to SGSI or OBO to get it whitelisted and explain them the situation.

**Comment by Hokkaydo** [comment]
After some discussion, this is most likely due to eduroam's firewall protecting from potential spoofing originating from multiple redirections

**Comment by Hokkaydo** [comment]
Fixed thanks to OBO's magic!
A derogation has been added to the firewalls
