### ISSUE TITLE
ADE Scheduler manque à la liste :-(

### ISSUE THREAD

**Issue by jeertmans** [EPLStudents/eplstudents.github.io#7]
Hello, très chouette site par ailleurs !

> Ce site recense tous les projets inventés par la communauté étudiante de l'EPL

Si ça rentre dans vos critères, ADE Scheduler a été créé par 3 étudiants EPL en 2019. D'ailleurs, on est toujours tous les 3 des étudiants (doctorants) à l'EPL :-P

**Comment by SnaKyEyeS** [comment]
Je plussoie (cé honteux) !

**Comment by Hokkaydo** [comment]
Milles excuses, c'est carrément honteux 
Merci beaucoup à vous pour ce merveilleux outil.
Ça arrive dans la soirée ;) 

*N'hésitez pas à passer sur le Discord au passage, il a bien changé depuis 2021*
